Updating Models to allow for nested attributes
CodeTheDream/wiki-med pull request #31
Opened 2019-04-03 16:34 UTC by camidemery

2019-04-04 21:46 UTC, leila-alderman commented
It looks like you created this branch off of your last feature branch instead of creating it off of master. 

Could you please update this branch so that it shows only the relevant changes and the changes that you made in the last PR?

Now that your last PR has been merged, you can do this with
`git checkout master`
`git pull upstream master`
`git checkout models`
`git merge master`

2019-04-05 18:31 UTC, leila-alderman requested changes
Looks good! Just some very minor spacing issues.

2019-04-05 18:31 UTC, leila-alderman commented on app/models/facility.rb
> +    has_many :bills
[Style]
Please fix the spacing here so that the indentation is 2 spaces, not four.

2019-04-05 18:31 UTC, leila-alderman commented on app/models/item.rb
> +      belongs_to :bill
[Style]
Please fix the spacing here so that the indentation is 2 spaces, not six.

2019-04-05 18:31 UTC, leila-alderman commented on app/models/item.rb
> +    validates :name, :description, :price, presence: true
[Style]
Please fix the spacing here so that the indentation is 2 spaces, not four.

2019-04-08 14:39 UTC, camidemery commented
Issues have been fixed on master already

2019-04-08 14:39 UTC, closed without merging