Updating Views
CodeTheDream/wiki-med pull request #7
Opened 2019-03-21 16:54 UTC by camidemery

Increasing efficiency

2019-03-25 15:17 UTC, leila-alderman requested changes
The only two major things that need to be changed are updating to strong parameters and providing an argument for `Procedure.find` in the Procedures controller.

My other comments are more minor notes related to code style and simplifying. 

As always, please let me know if you have any questions or want to discuss further!

2019-03-25 15:17 UTC, leila-alderman commented on app/controllers/items_controller.rb
>      end
[Style] Ruby code should be [indented 2 spaces, not 4](https://github.com/rubocop-hq/ruby-style-guide#spaces-indentation).

You can change this setting in your IDE to make it the default for Ruby files.

2019-03-25 15:17 UTC, leila-alderman commented on app/controllers/items_controller.rb
>      end
Please update all of the controllers to use strong parameters. If you need some guidance on this, let me know. Thanks!

2019-03-25 15:17 UTC, leila-alderman commented on app/controllers/procedures_controller.rb
> +        procedure = Procedure.find
The `.find` method requires an argument.

2019-03-25 15:17 UTC, leila-alderman commented on app/views/facilities/_form.html.erb
> +    </div>
To add an HTML class to a Rails form, you can do it in a more Rails-y way with cleaner syntax (allowing you to remove all of the <div>s):

`<%= f.text_field  :name ,placeholder: "Name of Facility", class: 'p-2' %>`

2019-03-25 15:17 UTC, leila-alderman commented on app/views/facilities/edit.html.erb
> +<%= render 'form' %>
Nice change!

2019-03-25 15:17 UTC, leila-alderman commented on app/views/facilities/index.html.erb
> +        <h4 class=''><%=f.name%></h4>
If the class here is empty, you should be able to remove it altogether
```suggestion
        <h4><%=f.name%></h4>
```

2019-03-25 15:17 UTC, leila-alderman commented on app/views/items/_form.html.erb
> +  <div class="p-2"><%= f.number_field :price, placeholder: 'Price', min: 0, step: 0.01 %></div>
As mentioned above, you can make these form statements more succinct by moving the `class` into the form helper.

2019-03-25 15:17 UTC, leila-alderman commented on app/views/items/_form.html.erb
> +     </select>
Check out this Stack Overflow post on [how to create a dropdown in Rails](https://stackoverflow.com/questions/14113057/how-to-have-a-drop-down-select-field-in-a-rails-form).

2019-03-25 15:17 UTC, leila-alderman commented on app/views/items/new.html.erb
> +</container>
What do the `<container>` tags here do? (I'm wondering if they can be deleted or if they're needed for something else that's happening.)

2019-03-25 15:17 UTC, leila-alderman commented on app/views/procedures/_form.html.erb
> +</div>
You should be able to add the `class='p-2'` to the list of classes already on the submit button to simplify the code.

2019-03-25 15:17 UTC, leila-alderman commented on app/views/procedures/edit.html.erb
> +</container>
Again, are these `<container>` tags needed?

2019-03-25 15:17 UTC, leila-alderman commented on app/views/procedures/index.html.erb
> +            </div>
Can this empty `<div>` be deleted?

2019-03-25 15:17 UTC, leila-alderman commented on app/views/procedures/new.html.erb
> +</container>
Again, are these `<container>` tags needed?

2019-03-27 17:22 UTC, camidemery commented
Going to re-update views after models are redone

2019-03-27 17:22 UTC, closed without merging